# Generated by Django 3.0.2 on 2020-02-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200208_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
