# Generated by Django 3.0.2 on 2020-02-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_instructor',
        ),
    ]
