# Generated by Django 3.0.2 on 2020-02-05 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('inst', '0002_instructor_photo'),
        ('courses', '0003_remove_course_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strat_date', models.DateField()),
                ('end_date', models.DateField()),
                ('class_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inst.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enroll', models.DateField()),
                ('course_enroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.ClassGroup')),
                ('student_enroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(through='courses.Enrollment', to='student.Student'),
        ),
    ]
