# Generated by Django 3.0.2 on 2020-02-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='days_of_week',
            field=models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classgroup',
            name='sessionCount',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
