# Generated by Django 3.0.2 on 2020-02-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200207_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='days',
            field=models.ManyToManyField(to='courses.WeekDays'),
        ),
    ]
