# Generated by Django 3.0.2 on 2020-02-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200207_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='days_of_week',
            field=models.CharField(max_length=8),
        ),
    ]
