# Generated by Django 3.0.2 on 2020-02-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200207_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='days',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=2, max_length=1, unique=True),
            preserve_default=False,
        ),
    ]
