# Generated by Django 3.0.2 on 2020-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200207_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='days',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=1),
        ),
    ]
