# Generated by Django 3.0.2 on 2020-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200207_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='days',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
