# Generated by Django 3.0.2 on 2020-02-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200207_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
        migrations.RenameModel(
            old_name='WeekDays',
            new_name='Weekday',
        ),
        migrations.RenameField(
            model_name='classgroup',
            old_name='sessionCount',
            new_name='session_count',
        ),
    ]
