# Generated by Django 3.0.2 on 2020-02-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200207_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classgroup',
            old_name='strat_date',
            new_name='start_date',
        ),
    ]
