# Generated by Django 3.0.2 on 2020-02-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
    ]
