# Generated by Django 3.0.2 on 2020-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
