# Generated by Django 3.0.2 on 2020-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0002_instructor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='date_of_birth',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
