# Generated by Django 3.0.2 on 2020-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0003_auto_20200206_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='summary',
            field=models.TextField(default="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here,"),
            preserve_default=False,
        ),
    ]
