# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-10 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200210_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 13, 29, 35, 341395)),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to=b'post_img/'),
        ),
    ]
