# Generated by Django 3.0.2 on 2020-02-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_dob',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_mobile_phone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_fname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_lname',
        ),
    ]
